export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_LIST_MY_REQUEST = "ADMIN_LIST_MY_REQUEST";
export const ADMIN_LIST_MY_SUCCESS = "ADMIN_LIST_MY_SUCCESS";
export const ADMIN_LIST_MY_FAIL = "ADMIN_LIST_MY_FAIL";