//Get BOOKING
export const BOOKING_LIST_MY_REQUEST = "BOOKING_LIST_MY_REQUEST";
export const BOOKING_LIST_MY_SUCCESS = "BOOKING_LIST_MY_SUCCESS";
export const BOOKING_LIST_MY_FAIL = "BOOKING_LIST_MY_FAIL";
export const BOOKING_LIST_MY_RESET = "BOOKING_LIST_MY_RESET";
