//Add CITY
export const CITY_CREATE_REQUEST = "CITY_CREATE_REQUEST";
export const CITY_CREATE_SUCCESS = "CITY_CREATE_SUCCESS";
export const CITY_CREATE_FAIL = "CITY_CREATE_FAIL";
export const CITY_CREATE_RESET = "CITY_CREATE_RESET";

//Update CITY
export const CITY_UPDATE_REQUEST = "CITY_UPDATE_REQUEST";
export const CITY_UPDATE_SUCCESS = "CITY_UPDATE_SUCCESS";
export const CITY_UPDATE_FAIL = "CITY_UPDATE_FAIL";
export const CITY_UPDATE_RESET = "CITY_UPDATE_RESET";

//Delete CITY
export const CITY_DELETE_REQUEST = "CITY_DELETE_REQUEST";
export const CITY_DELETE_SUCCESS = "CITY_DELETE_SUCCESS";
export const CITY_DELETE_FAIL = "CITY_DELETE_FAIL";

//Get CITY
export const CITY_LIST_MY_REQUEST = "CITY_LIST_MY_REQUEST";
export const CITY_LIST_MY_SUCCESS = "CITY_LIST_MY_SUCCESS";
export const CITY_LIST_MY_FAIL = "CITY_LIST_MY_FAIL";
export const CITY_LIST_MY_RESET = "CITY_LIST_MY_RESET";

//Get CITY by Id
export const CITY_DETAILS_REQUEST = "CITY_DETAILS_REQUEST";
export const CITY_DETAILS_SUCCESS = "CITY_DETAILS_SUCCESS";
export const CITY_DETAILS_FAIL = "CITY_DETAILS_FAIL";

export const CLEAR = "CLEAR";
