//Add COMPANY
export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST";
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS";
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL";
export const COMPANY_CREATE_RESET = "COMPANY_CREATE_RESET";

//Update COMPANY
export const COMPANY_UPDATE_REQUEST = "COMPANY_UPDATE_REQUEST";
export const COMPANY_UPDATE_SUCCESS = "COMPANY_UPDATE_SUCCESS";
export const COMPANY_UPDATE_FAIL = "COMPANY_UPDATE_FAIL";
export const COMPANY_UPDATE_RESET = "COMPANY_UPDATE_RESET";

//Delete COMPANY
export const COMPANY_DELETE_REQUEST = "COMPANY_DELETE_REQUEST";
export const COMPANY_DELETE_SUCCESS = "COMPANY_DELETE_SUCCESS";
export const COMPANY_DELETE_FAIL = "COMPANY_DELETE_FAIL";

//Get COMPANY
export const COMPANY_LIST_MY_REQUEST = "COMPANY_LIST_MY_REQUEST";
export const COMPANY_LIST_MY_SUCCESS = "COMPANY_LIST_MY_SUCCESS";
export const COMPANY_LIST_MY_FAIL = "COMPANY_LIST_MY_FAIL";
export const COMPANY_LIST_MY_RESET = "COMPANY_LIST_MY_RESET";

//Get COMPANY by Id
export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";
