//Add FAQCATEGORY
export const FAQCATEGORY_CREATE_REQUEST = "FAQCATEGORY_CREATE_REQUEST";
export const FAQCATEGORY_CREATE_SUCCESS = "FAQCATEGORY_CREATE_SUCCESS";
export const FAQCATEGORY_CREATE_FAIL = "FAQCATEGORY_CREATE_FAIL";
export const FAQCATEGORY_CREATE_RESET = "FAQCATEGORY_CREATE_RESET";

//Update FAQCATEGORY
export const FAQCATEGORY_UPDATE_REQUEST = "FAQCATEGORY_UPDATE_REQUEST";
export const FAQCATEGORY_UPDATE_SUCCESS = "FAQCATEGORY_UPDATE_SUCCESS";
export const FAQCATEGORY_UPDATE_FAIL = "FAQCATEGORY_UPDATE_FAIL";
export const FAQCATEGORY_UPDATE_RESET = "FAQCATEGORY_UPDATE_RESET";

//Delete FAQCATEGORY
export const FAQCATEGORY_DELETE_REQUEST = "FAQCATEGORY_DELETE_REQUEST";
export const FAQCATEGORY_DELETE_SUCCESS = "FAQCATEGORY_DELETE_SUCCESS";
export const FAQCATEGORY_DELETE_FAIL = "FAQCATEGORY_DELETE_FAIL";

//Get FAQCATEGORY
export const FAQCATEGORY_LIST_MY_REQUEST = "FAQCATEGORY_LIST_MY_REQUEST";
export const FAQCATEGORY_LIST_MY_SUCCESS = "FAQCATEGORY_LIST_MY_SUCCESS";
export const FAQCATEGORY_LIST_MY_FAIL = "FAQCATEGORY_LIST_MY_FAIL";
export const FAQCATEGORY_LIST_MY_RESET = "FAQCATEGORY_LIST_MY_RESET";

//Get FAQCATEGORY by Id
export const FAQCATEGORY_DETAILS_REQUEST = "FAQCATEGORY_DETAILS_REQUEST";
export const FAQCATEGORY_DETAILS_SUCCESS = "FAQCATEGORY_DETAILS_SUCCESS";
export const FAQCATEGORY_DETAILS_FAIL = "FAQCATEGORY_DETAILS_FAIL";
