//Add VEHICLE
export const VEHICLE_CREATE_REQUEST = "VEHICLE_CREATE_REQUEST";
export const VEHICLE_CREATE_SUCCESS = "VEHICLE_CREATE_SUCCESS";
export const VEHICLE_CREATE_FAIL = "VEHICLE_CREATE_FAIL";
export const VEHICLE_CREATE_RESET = "VEHICLE_CREATE_RESET";

//Update VEHICLE
export const VEHICLE_UPDATE_REQUEST = "VEHICLE_UPDATE_REQUEST";
export const VEHICLE_UPDATE_SUCCESS = "VEHICLE_UPDATE_SUCCESS";
export const VEHICLE_UPDATE_FAIL = "VEHICLE_UPDATE_FAIL";
export const VEHICLE_UPDATE_RESET = "VEHICLE_UPDATE_RESET";

//Delete VEHICLE
export const VEHICLE_DELETE_REQUEST = "VEHICLE_DELETE_REQUEST";
export const VEHICLE_DELETE_SUCCESS = "VEHICLE_DELETE_SUCCESS";
export const VEHICLE_DELETE_FAIL = "VEHICLE_DELETE_FAIL";

//Get VEHICLE
export const VEHICLE_LIST_MY_REQUEST = "VEHICLE_LIST_MY_REQUEST";
export const VEHICLE_LIST_MY_SUCCESS = "VEHICLE_LIST_MY_SUCCESS";
export const VEHICLE_LIST_MY_FAIL = "VEHICLE_LIST_MY_FAIL";
export const VEHICLE_LIST_MY_RESET = "VEHICLE_LIST_MY_RESET";

//Get VEHICLE by Id
export const VEHICLE_DETAILS_REQUEST = "VEHICLE_DETAILS_REQUEST";
export const VEHICLE_DETAILS_SUCCESS = "VEHICLE_DETAILS_SUCCESS";
export const VEHICLE_DETAILS_FAIL = "VEHICLE_DETAILS_FAIL";
