//Add VEHICLETYPE
export const VEHICLETYPE_CREATE_REQUEST = "VEHICLETYPE_CREATE_REQUEST";
export const VEHICLETYPE_CREATE_SUCCESS = "VEHICLETYPE_CREATE_SUCCESS";
export const VEHICLETYPE_CREATE_FAIL = "VEHICLETYPE_CREATE_FAIL";
export const VEHICLETYPE_CREATE_RESET = "VEHICLETYPE_CREATE_RESET";

//Update VEHICLETYPE
export const VEHICLETYPE_UPDATE_REQUEST = "VEHICLETYPE_UPDATE_REQUEST";
export const VEHICLETYPE_UPDATE_SUCCESS = "VEHICLETYPE_UPDATE_SUCCESS";
export const VEHICLETYPE_UPDATE_FAIL = "VEHICLETYPE_UPDATE_FAIL";
export const VEHICLETYPE_UPDATE_RESET = "VEHICLETYPE_UPDATE_RESET";

//Delete VEHICLETYPE
export const VEHICLETYPE_DELETE_REQUEST = "VEHICLETYPE_DELETE_REQUEST";
export const VEHICLETYPE_DELETE_SUCCESS = "VEHICLETYPE_DELETE_SUCCESS";
export const VEHICLETYPE_DELETE_FAIL = "VEHICLETYPE_DELETE_FAIL";

//Get VEHICLETYPE
export const VEHICLETYPE_LIST_MY_REQUEST = "VEHICLETYPE_LIST_MY_REQUEST";
export const VEHICLETYPE_LIST_MY_SUCCESS = "VEHICLETYPE_LIST_MY_SUCCESS";
export const VEHICLETYPE_LIST_MY_FAIL = "VEHICLETYPE_LIST_MY_FAIL";
export const VEHICLETYPE_LIST_MY_RESET = "VEHICLETYPE_LIST_MY_RESET";

//Get VEHICLETYPE by Id
export const VEHICLETYPE_DETAILS_REQUEST = "VEHICLETYPE_DETAILS_REQUEST";
export const VEHICLETYPE_DETAILS_SUCCESS = "VEHICLETYPE_DETAILS_SUCCESS";
export const VEHICLETYPE_DETAILS_FAIL = "VEHICLETYPE_DETAILS_FAIL";
