export const STATE_CREATE_REQUEST = "STATE_CREATE_REQUEST";
export const STATE_CREATE_SUCCESS = "STATE_CREATE_SUCCESS";
export const STATE_CREATE_FAIL = "STATE_CREATE_FAIL";

export const STATE_LIST_MY_REQUEST = "STATE_LIST_MY_REQUEST";
export const STATE_LIST_MY_SUCCESS = "STATE_LIST_MY_SUCCESS";
export const STATE_LIST_MY_FAIL = "STATE_LIST_MY_FAIL";
export const STATE_LIST_MY_RESET = "STATE_LIST_MY_RESET";