//Add State
export const STATE_CREATE_REQUEST = "STATE_CREATE_REQUEST";
export const STATE_CREATE_SUCCESS = "STATE_CREATE_SUCCESS";
export const STATE_CREATE_FAIL = "STATE_CREATE_FAIL";

//Update State
export const STATE_UPDATE_REQUEST = "STATE_UPDATE_REQUEST";
export const STATE_UPDATE_SUCCESS = "STATE_UPDATE_SUCCESS";
export const STATE_UPDATE_FAIL = "STATE_UPDATE_FAIL";
export const STATE_UPDATE_RESET = "STATE_UPDATE_FAIL";

//Delete State
export const STATE_DELETE_REQUEST = "STATE_DELETE_REQUEST";
export const STATE_DELETE_SUCCESS = "STATE_DELETE_SUCCESS";
export const STATE_DELETE_FAIL = "STATE_DELETE_FAIL";

//Get State
export const STATE_LIST_MY_REQUEST = "STATE_LIST_MY_REQUEST";
export const STATE_LIST_MY_SUCCESS = "STATE_LIST_MY_SUCCESS";
export const STATE_LIST_MY_FAIL = "STATE_LIST_MY_FAIL";
export const STATE_LIST_MY_RESET = "STATE_LIST_MY_RESET";

//Get State by Id
export const STATE_DETAILS_REQUEST = "STATE_DETAILS_REQUEST";
export const STATE_DETAILS_SUCCESS = "STATE_DETAILS_SUCCESS";
export const STATE_DETAILS_FAIL = "STATE_DETAILS_FAIL";