export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LIST_MY_REQUEST = "USER_LIST_MY_REQUEST";
export const USER_LIST_MY_SUCCESS = "USER_LIST_MY_SUCCESS";
export const USER_LIST_MY_FAIL = "USER_LIST_MY_FAIL";