//Add BOOKING
export const BOOKING_CREATE_REQUEST = "BOOKING_CREATE_REQUEST";
export const BOOKING_CREATE_SUCCESS = "BOOKING_CREATE_SUCCESS";
export const BOOKING_CREATE_FAIL = "BOOKING_CREATE_FAIL";
export const BOOKING_CREATE_RESET = "BOOKING_CREATE_RESET";

//Update BOOKING
export const BOOKING_UPDATE_REQUEST = "BOOKING_UPDATE_REQUEST";
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";
export const BOOKING_UPDATE_FAIL = "BOOKING_UPDATE_FAIL";
export const BOOKING_UPDATE_RESET = "BOOKING_UPDATE_RESET";

//Delete BOOKING
export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";

//Get BOOKING by userId
export const BOOKINGBYUSER_DETAILS_REQUEST = "BOOKINGBYUSER_DETAILS_REQUEST";
export const BOOKINGBYUSER_DETAILS_SUCCESS = "BOOKINGBYUSER_DETAILS_SUCCESS";
export const BOOKINGBYUSER_DETAILS_FAIL = "BOOKINGBYUSER_DETAILS_FAIL";
export const BOOKINGBYUSER_LIST_MY_RESET = "BOOKINGBYUSER_LIST_MY_RESET";
