//LOGIN USER
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

//FORGET PASSWORD
export const FORGETPASSWORD_REQUEST = "FORGETPASSWORD_REQUEST";
export const FORGETPASSWORD_SUCCESS = "FORGETPASSWORD_SUCCESS";
export const FORGETPASSWORD_FAIL = "FORGETPASSWORD_FAIL";

//OTP
export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAIL = "OTP_FAIL";

//CHANGE PASSWORD
export const CHANGEPASSWORD_REQUEST = "CHANGEPASSWORD_REQUEST";
export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS";
export const CHANGEPASSWORD_FAIL = "CHANGEPASSWORD_FAIL";

//Add USER
export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

//LIST USER
export const USER_LIST_MY_REQUEST = "USER_LIST_MY_REQUEST";
export const USER_LIST_MY_SUCCESS = "USER_LIST_MY_SUCCESS";
export const USER_LIST_MY_FAIL = "USER_LIST_MY_FAIL";
export const USER_LIST_MY_RESET = "USER_LIST_MY_RESET";

//Update USER
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

//Delete USER
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

//Get USER by Id
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

//Get Vehicle by CompanyId
export const VEHICLEBYCOMPANY_DETAILS_REQUEST =
  "VEHICLEBYCOMPANY_DETAILS_REQUEST";
export const VEHICLEBYCOMPANY_DETAILS_SUCCESS =
  "VEHICLEBYCOMPANY_DETAILS_SUCCESS";
export const VEHICLEBYCOMPANY_DETAILS_FAIL = "VEHICLEBYCOMPANY_DETAILS_FAIL";

//Get Vehicle by TypeId
export const VEHICLEBYTYPE_DETAILS_REQUEST =
  "VEHICLEBYTYPE_DETAILS_REQUEST";
export const VEHICLEBYTYPE_DETAILS_SUCCESS =
  "VEHICLEBYTYPE_DETAILS_SUCCESS";
export const VEHICLEBYTYPE_DETAILS_FAIL = "VEHICLEBYTYPE_DETAILS_FAIL";

//Get FAQ by FaqCategoryId
export const FAQBYFAQCATEGORY_DETAILS_REQUEST =
  "FAQBYFAQCATEGORY_DETAILS_REQUEST";
export const FAQBYFAQCATEGORY_DETAILS_SUCCESS =
  "FAQBYFAQCATEGORY_DETAILS_SUCCESS";
export const FAQBYFAQCATEGORY_DETAILS_FAIL = "FAQBYFAQCATEGORY_DETAILS_FAIL";
